module.exports = {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREASE_ITEM: 'INCREASE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',
    ADD_NOTE:'ADD_NOTE',
    CHANGE_NOTE:'CHANGE_NOTE'
};
